# Generated by Django 3.1 on 2020-09-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('products_image', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_image')),
                ('price', models.FloatField()),
                ('span_price', models.FloatField()),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
