# Generated by Django 3.1 on 2020-09-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=500)),
                ('p_name', models.CharField(max_length=500)),
                ('totalamount', models.FloatField()),
                ('purchased_time', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('custmer_email', models.EmailField(max_length=500)),
            ],
        ),
    ]
